apiVersion: apps/v1
kind: Deployment

metadata:
  name: unilab-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: unilab-backend

  template:
    metadata:
      labels:
        app: unilab-backend

    spec:
      containers:
        - name: backend

          image: proyectosw-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8000
            - containerPort: 5005
              protocol: UDP

          env:
            - name: ENVIRONMENT
              value: "production"

            - name: LOG_LEVEL
              value: "info"